### ISSUE TITLE
Improvements for player graphs

### ISSUE THREAD

**Issue by cscheid** [bddicken/nba-game-vis#7]
It would be nice to use a better algorithm for positioning the nodes of the graph.

Stress majorization is the default solution, and for few nodes (~30-50 or so) there are simple iterative algorithms that do the job well. The paper is here http://www.graphviz.org/Documentation/GKN04.pdf

**Comment by cscheid** [comment]
Maybe even use the distances directly, using t-SNE or something simillar (http://cs.stanford.edu/people/karpathy/tsnejs/wordvecs.html)  https://github.com/karpathy/tsnejs

**Comment by bddicken** [comment]
Implemented as of commit ae1fbc330322aeb3952182f2d7069815ca6ea2d4.
